using System.ComponentModel.DataAnnotations;
using FinBookeAPI.Models.Authentication;

namespace FinBookeAPI.DTO.Authentication;

/// <summary>
/// The class <c>ResetPasswordDTO</c> models a transfer object to reset the password.
/// </summary>
public class ResetPasswordDTO
{
    /// <summary>
    /// The email address of the user account.
    /// </summary>
    [Required(ErrorMessage = "Email property is missing")]
    [EmailAddress(ErrorMessage = "Email property should be a valid email address")]
    public string Email { get; set; } = "";

    /// <summary>
    /// The security code generated by the server and sent via email.
    /// </summary>
    [Required(ErrorMessage = "Code property is missing")]
    public string Code { get; set; } = "";

    /// <summary>
    /// This method converts the current <c>ResetPasswordDTO</c> instance into an object that
    /// can be processed by the provided <c>AuthenticationService</c>.
    /// </summary>
    /// <returns>
    /// The object which can be used in the <c>AuthenticationService</c>.
    /// </returns>
    public UserResetRequest GetUserResetRequest()
    {
        return new UserResetRequest { Email = Email, Code = Code };
    }
}
