#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## husky task runner examples -------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'

echo "#########################################################################################\n"
echo "\t\t\t\033[1mStarting to lint the current code files\033[0m"
echo "\n#########################################################################################\n\n"

staged=$(git diff --name-only | wc -l)
dotnet csharpier .
changed=$(git diff --name-only | wc -l)
if [ $staged -ne $changed ]; then
    echo "\033[0;31mFiles have been modified by csharpier. Please stage them again before committing"
    exit 1
fi
echo "\n"

echo "#########################################################################################\n"
echo "\t\t\t\t\033[1mExecute all tests\033[0m"
echo "\n#########################################################################################\n\n"

dotnet test backend-finbookeapp.csproj